### ISSUE TITLE
[CY-3403] [Feature request] eslint-plugin-functional

### ISSUE THREAD

**Issue by rivy** [codacy/codacy-eslint#1012]
We're using the [eslint-plugin-functional](https://www.npmjs.com/package/eslint-plugin-functional) plugin to encourage functional programming style; it would be great if you would include it as an installed (optional) plugin.

Thanks.

**Comment by lolgab** [comment]
Fixed in #1018

**Comment by rivy** [comment]
Thanks for the *very rapid* response.

**Comment by lolgab** [comment]
Glad we could help!
