### ISSUE TITLE
[CY-4459] Prettier version conflict.

### ISSUE THREAD

**Issue by simoneBrancati** [codacy/codacy-eslint#1501]
Hi,
after we updated **prettier** to version 2.3.1, Codacy has started opening issues and suggesting style changes in conflict with this version.
I noticed that Codacy is still locked to prettier 2.2.1.
Can you please update?

Thank you in advance.

**Comment by franciscodua** [comment]
The version currently available in production is already up to date.

Let us know if you still hit any problems, or if the update fixed them.
