### ISSUE TITLE
[CY-5848] Eslint 8

### ISSUE THREAD

**Issue by Covalent-DonR** [codacy/codacy-eslint#2363]
Hello, 

eslint 8 was released in October 2021 and this repo is still on version 7. Is there an issue with this upgrade? When will the upgrade be completed? Would you add a note / pinned issue in github communicating when the update will be completed? 

Thank you

**Comment by lolgab** [comment]
@Covalent-DonR We released ESLint 8 as a new tool in Codacy. You need to disable `ESLint (Legacy) 7` and enable `ESLint 8` in your repository's `Code Patterns` page.
