### ISSUE TITLE
Add eslint-import-resolver-alias

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-eslint#244]

**Comment by stephen333** [comment]
This is odd, I thought this issue was previously solved with #240 ?

**Comment by lolgab** [comment]
My fault, I had to link the PR with the issue. The problem is because when we merge a new version of a tool we need to put in our infrastructure, test it, etc.
This process takes time. You can expect a new version to be released next week.
I will close this issue when the new version is online with your fix.

Lorenzo
