### ISSUE TITLE
[CY-5968] Add support for `es` plugin

### ISSUE THREAD

**Issue by dguettler** [codacy/codacy-eslint#2453]
Hello,

please add support for `es` plugin.

Thank you,
Daniel

**Comment by dguettler** [comment]
Looks like `ember` is already supported, removed from the issue description

**Comment by stefanvacareanu7** [comment]
Hi there,

Thanks for reaching out to our community!

I am going to pass your proposal to the Engineering Team for further consideration.

Any other contribution is really appreciated.

Best,
Stefan

**Comment by lolgab** [comment]
@dguettler Is [this](https://github.com/mysticatea/eslint-plugin-es) the plugin you're asking to support?

**Comment by dguettler** [comment]
yes

**Comment by lolgab** [comment]
The `es` ESLint plugin is now released on `codacy.com`.

**Comment by dguettler** [comment]
Thank you for the quick turnaround. 
@lolgab are those changes live yet? As of an hour ago I'm setting running into this error
```
KubernetesDockerRunner: Container for codacy/codacy-eslint:9.0.14 exited with non-zero code 1
Error: Failed to load plugin 'es' declared in '.eslintrc.js': Cannot find module 'eslint-plugin-es'
Require stack:
- /__placeholder__.js
Referenced from: /src/.eslintrc.js
```

**Comment by dguettler** [comment]
Ok guess the question is how do I tell it to use version 9.1.0 vs 9.0.14?

**Comment by lolgab** [comment]
My bad, the update wasn't deployed. Now it is deployed and the plugin should be available.

**Comment by lolgab** [comment]
> Ok guess the question is how do I tell it to use version 9.1.0 vs 9.0.14?

It is decided internally and the used images are listed in [Codacy's tools API](https://app.codacy.com/api/v3/tools).
