### ISSUE TITLE
[CY-6416] Add maintained Cypress plugin

### ISSUE THREAD

**Issue by bmulholland** [codacy/codacy-eslint#3022]
[eslint-plugin-cypress isn't maintained](https://github.com/cypress-io/eslint-plugin-cypress/issues/100), and the replacement is @finsit/eslint-plugin-cypress

**Comment by stefanvacareanu7** [comment]
Hi there,

Thanks for reaching out!

We modified the plugin as you suggested.

I am closing the ticket, but feel free to add any information if any other issue arises.

Keep up the good work!

Stefan
