### ISSUE TITLE
[CY-6561] Add eslint plugin: typescript-sort-keys

### ISSUE THREAD

**Issue by fabfuel** [codacy/codacy-eslint#3283]
Hi there!

We're evaluating Codacy for one of our typescript projects and can not yet run eslint validation, because we're using the [`typescript-sort-keys`](https://www.npmjs.com/package/eslint-plugin-typescript-sort-keys) plugin. Would it be possible to add this plugin to the Codacy eslint runner?

Thanks in advance and best wishes from Berlin
Fabian

**Comment by stefanvacareanu7** [comment]
Hi there,

The plugin typescript-sort-keys is not part of codacy-eslint.

Best,
Stefan

**Comment by fabfuel** [comment]
I assume you meant "is now part" :-)
Works like a charm, thanks a lot @stefanvacareanu7!
