### ISSUE TITLE
[CY-6570] Add plugin: prettier-plugin-tailwindcss

### ISSUE THREAD

**Issue by fabfuel** [codacy/codacy-eslint#3309]
Hi there!

We're evaluating Codacy for one of our typescript projects and can not yet run eslint validation, because we're using [prettier-plugin-tailwindcss](https://www.npmjs.com/package/prettier-plugin-tailwindcss). Would it be possible to add this plugin to the Codacy eslint runner?

Thanks in advance and best wishes from Berlin
Fabian

**Comment by stefanvacareanu7** [comment]
Hi there,

We just added prettier-plugin-tailwindcss to the tool.

Best,
Stefan
