### ISSUE TITLE
[CY-6575] Add plugins: eslint-plugin-markdown & eslint-plugin-yml

### ISSUE THREAD

**Issue by tonec** [codacy/codacy-eslint#3339]
Hi,
This is related to the following ticket: https://codacy.zendesk.com/hc/en-us/requests/30950

Codacy is in use on a number of repositories I'm working on. However, now all of the linting issues are being picked up by Codacy. 

One possibly reason for this is that we're using the following eslint plugins, which don't appear to be included in your dependency list:

- eslint-plugin-markdown
- eslint-plugin-yml

Can these be added please?

Thanks
Tony

**Comment by stefanvacareanu7** [comment]
Hello,

I just added eslint-plugin-markdown to the tool. Unfortunately, for eslint-plugin-yml I still have some difficulties, reason why it's going to take a bit longer.

I'll keep you posted when it's done.

Best,
Stefan

**Comment by codacy-vrhpires** [comment]
Hello.
They've both been added.

Best regards,
Vítor
