### ISSUE TITLE
[TS-527] Please add shakapacker

### ISSUE THREAD

**Issue by Covalent-DonR** [codacy/codacy-eslint#4050]
Hello,

Rails has a semi-official webpack wrapper called Shakapacker (https://github.com/shakacode/shakapacker) that provides an NPM package named "shakapacker". 

This npm package is used in webpack.config.js to load some default configuration. As the eslint-plugin-import reads the webpack.config.js file, this currently errors in codacy with `Resolve error: Cannot find module 'shakapacker' Require stack: - /src/config/webpack/webpack.config.js [...]`. 

Could you please add the NPM package `shakapacker` to this repo so that our project can continue to use eslint-plugin-import in codacy? Thank you!

**Comment by codacy-vrhpires** [comment]
Hello.
It has been added:
https://github.com/codacy/codacy-eslint/blob/56e83bd601812c0030760715d3bab3a8377b53db/package.json#L325
