### ISSUE TITLE
[TCE-792] DOes Codacy recognizes the new "flat config" format for Eslint?

### ISSUE THREAD

**Issue by stefanobartoletti** [codacy/codacy-eslint#4306]
As the title says, is the new "flat config" format recognized by Codacy?

I'm talking about this, that will become the default format in the upcoming v 9: https://eslint.org/docs/latest/use/configure/configuration-files-new

At the moment I'm using it in a couple of my open-source projects, and even if I can use Eslint correctly with it both in my laptop and on the automated CI workflows here on GitHub, Codacy does not seem to find it and use it to report possible linting and style errors.

**Comment by codacy-vrhpires** [comment]
Hello @stefanobartoletti 
It will be supported after ESLint 9 launches and we release shortly after a new tool based on that version.

**Comment by stefanobartoletti** [comment]
@codacy-vrhpires thanks!
