### ISSUE TITLE
Codacy doesn't read Babel plugin's babelrc/eslint configuration file

### ISSUE THREAD

**Issue by lapa182** [codacy/codacy-eslint#45]
Hey guys, after the new release our analysis are not running correct due to the following error

`Resolve error: Cannot find module 'babel-plugin-module-resolver' Require stack: - /node_modules/eslint-import-resolver-babel-module/lib/index.js - /node_modules/eslint-module-utils/resolve.js - /node_modules/eslint-plugin-import/lib/rules/no-unresolved.js - /node_modules/eslint-plugin-import/lib/index.js - /node_modules/eslint/lib/cli-engine/config-array-factory.js - /node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js - /node_modules/eslint/lib/cli-engine/cli-engine.js - /node_modules/esli`

Even so it exists inside your package.json here in codacy-eslint, we had to reduce the quality level to get our PR's merged because of this.

**Comment by lolgab** [comment]
Hi @lapa182,
Thank you for opening the issue.
It seems very strange, we added the babel plugin some days ago and they are running on production. When did you analyse? Maybe before the new version of the tool?
Are you able to reproduce it? If you could push a reproduction somewhere, it would be awesome!

**Comment by lapa182** [comment]
Hey @lolgab, is happening in all our new analysis. One of my colleagues is in touch via the support channel and sent the link to you guys (https://app.codacy.com/manual/harveynichols/ff/pullRequest?prid=4749638). And because of this error we are having a lot of "unable to resolve path", because we use alias inside our .babelrc.

**Comment by lapa182** [comment]
@lolgab  just re-run an analyse and seems to be working now! Will close the issue :).

**Comment by lapa182** [comment]
@lolgab Sorry for the closing/re-opening. The error is gone, but doesn't seem Codacy is reading the babelrc/eslint from our project, as you can check here: 

<img width="1316" alt="Screenshot 2019-12-31 at 12 29 29" src="https://user-images.githubusercontent.com/2954009/71621782-42f51400-2bc9-11ea-86d7-4e04598f60a9.png">

and

<img width="1319" alt="Screenshot 2019-12-31 at 12 30 12" src="https://user-images.githubusercontent.com/2954009/71621791-4ee0d600-2bc9-11ea-81ba-30a3dba62c79.png">

**Comment by lapa182** [comment]
Not sure if it's the same issue, but we are also having issues with

```Unable to resolve path to module 'react'.``` and other paths as well, even so it was working before.

**Comment by paulacodacy** [comment]
Hello @lapa182, 

Letting you know that as for your last question, I've got in contact with Adam from your team and replied back to him. 

Regards,
Paula

**Comment by lolgab** [comment]
Hi @lapa182,
About the false positives like `Unable to resolve path to module 'react'.` we already merged a [fix]
(https://github.com/codacy/codacy-eslint/pull/101) and it's going to production.
Lorenzo
