### ISSUE TITLE
You might need eslint-import-resolver-typescript

### ISSUE THREAD

**Issue by LeafHacker** [codacy/codacy-eslint#53]
In my eslint config, I've [had to specify](https://github.com/ImpactDevelopment/Website/commit/635fea4e0bf5c8fac9a406c4f46106effcc372fa#diff-0378d5111ab996d5882f4712e9350604R55) `eslint-import-resolver-typescript` to get `eslint-plugin-import` working properly with typescript. 

I assume you may need to do the same as I get a bunch of false-positives from `eslint-plugin-import` in my codacy that I don't see when running eslint myself.

**Comment by lolgab** [comment]
Thank you for your suggestion @LeafHacker :)
I opened a PR which should solve the issue #55
