### ISSUE TITLE
[Bug] package.json overiting eslint settings on codacy

### ISSUE THREAD

**Issue by anthony0030** [codacy/codacy-eslint#609]
I am getting code styling errors on Codacy.

I believe it is this setting in the package.json file

```
"prettier": {
  "semi": false
},
```

**Comment by lolgab** [comment]
Hi @anthony0030,
Try to add the latest version of prettier to you project. Prettier changed its defaults from version `1.x` to version `2.x`. Could be that one of you packages depends on Prettier `1.x`, so you are getting different results in Codacy.

**Comment by anthony0030** [comment]
I am using: 
"eslint-config-prettier": "^6.11.0",
"eslint-plugin-prettier": "^3.1.4",
"prettier": "^2.0.5",

**Comment by lolgab** [comment]
This issue should be solved with the last update.
Feel free to reopen it in case you continue to face this problem.

**Comment by anthony0030** [comment]
Thank you  @lolgab :)
