### ISSUE TITLE
[CY-2437] [codacy-eslint] Does not support shared eslint config

### ISSUE THREAD

**Issue by rmg** [codacy/codacy-eslint#664]
Projects that have multiple repositories and individuals seeking to reduce their overhead have adopted [shared eslint configurations](http://eslint.org/docs/user-guide/configuring#extending-configuration-files).

When Codacy scans a project that uses shared rules it appears to scan without any rules enabled at all, which catches nothing.

Supporting this would require that the scanner install a project's `devDependencies` as part of the scanning process.

As an example, I opened a PR in a repo that uses shared rules and no issues were found. I then added a commit that pulled all the rules in-line in to the `.eslintrc` and it hit the expected errors: https://github.com/strongloop/strong-tools/pull/73

**Comment by franciscodua** [comment]
Hi
This issue has been inactive for a long time now. 
Regarding your concerns, unfortunately, we still maintain this limitation of not being able to connect to the internet to fetch your shared configurations.

We're working on ways to give you more flexibility on how these tools are run. We appreciate this feedback and we'll take it into consideration for our next steps.

I hope we can come back to you soon with good news about this (and this time we'll try to be faster than the time we took to answer this issue 😅 )
Meanwhile, I'll close this issue
