### ISSUE TITLE
[CY-2653]  [Feature Request] better-styled-components

### ISSUE THREAD

**Issue by oherik** [codacy/codacy-eslint#689]
The analysis fails with the following error:

```
Error: Failed to load plugin 'better-styled-components' declared in '.eslintrc.json': Cannot find module 'eslint-plugin-better-styled-components'
```

Would it be possible to add this as a dependency?

**Comment by machadoit** [comment]
Hi @oherik,

We will be adding better-styled-components at https://github.com/codacy/codacy-eslint/pull/692

**Comment by oherik** [comment]
Thank you @machadoit!

**Comment by franciscodua** [comment]
Closing this issue, since the plugin should be available by now.
Thank you for the suggestion
